name: Build and Push to ACR
 
on:
  push:
    branches: ["main"]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      - name: Build and Push to ACR
        uses: azure/docker-login@v1
        with:
          login-server: registering.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
 
      - run: |
          docker build -t acr5376.azurecr.io/employee-basic:latest .
          docker push acr5376.azurecr.io/employee-basic:latest
